version: "3"

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    command: --innodb-use-native-aio=0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
    ports:
      - "33061:3306"
    networks:
      - network-desafio2

  nodejs:
    build: nodejs
    networks:
      - network-desafio2

  nginx:
    build: nginx
    ports:
      - 8000:80
    networks:
      - network-desafio2

networks:
  network-desafio2:
    driver: bridge
